# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-06 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nuser', '0001_initial'),
        ('DeviceManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renderstyle', models.CharField(default='', max_length=30, verbose_name='\u6e32\u67d3\u6837\u5f0f')),
                ('name', models.CharField(default='', max_length=30, verbose_name='\u7c7b\u578b\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u623f\u95f4\u7c7b\u578b',
                'verbose_name_plural': '\u623f\u95f4\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5206\u914d\u65f6\u95f4')),
                ('begin_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('remark', models.TextField(default='', verbose_name='\u5907\u6ce8')),
                ('fenpei', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fenpei_id', to='Nuser.User', verbose_name='\u5206\u914d\u4ebaID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='Nuser.User', verbose_name='\u8d1f\u8d23\u4ebaID')),
            ],
            options={
                'verbose_name': '\u7a7a\u95f4\u5206\u914d',
                'verbose_name_plural': '\u7a7a\u95f4\u5206\u914d',
            },
        ),
        migrations.CreateModel(
            name='SpaceBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='\u5b66\u6821\u540d', max_length=30, verbose_name='\u5b66\u6821\u540d')),
            ],
            options={
                'verbose_name': '\u6559\u5b66\u697c',
                'verbose_name_plural': '\u6559\u5b66\u697c',
            },
        ),
        migrations.CreateModel(
            name='SpaceFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='\u697c\u5c42')),
                ('model_Url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpaceManage.SpaceBuilding', verbose_name='\u6240\u5c5e\u6559\u5b66\u697c')),
            ],
            options={
                'verbose_name': '\u697c\u5c42',
                'verbose_name_plural': '\u697c\u5c42',
            },
        ),
        migrations.CreateModel(
            name='SpaceIbeacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibeacon_UUID', models.CharField(default='', max_length=30, verbose_name='\u8bbe\u5907\u552f\u4e00\u6807\u8bc6')),
                ('ibeacon_major', models.CharField(default='', max_length=30, verbose_name='\u81ea\u5b9a\u4e49\u6807\u8bc6')),
                ('ibeacon_minor', models.CharField(default='', max_length=30, verbose_name='\u81ea\u5b9a\u4e49\u6807\u8bc6\u7b26')),
                ('msg_template', models.TextField(default='', verbose_name='\u4fe1\u606f\u6a21\u677f')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DeviceManage.Device', verbose_name='\u5173\u8054\u8bbe\u5907')),
            ],
            options={
                'verbose_name': '\u7a7a\u95f4\u5b9a\u4f4d\u8bbe\u5907',
                'verbose_name_plural': '\u7a7a\u95f4\u5b9a\u4f4d\u8bbe\u5907',
            },
        ),
        migrations.CreateModel(
            name='SpaceRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(default=0, verbose_name='\u623f\u95f4\u53f7')),
                ('grossarea', models.IntegerField(default=0, verbose_name='\u5efa\u7b51\u9762\u79ef')),
                ('netarea', models.CharField(default=0, max_length=30, verbose_name='\u5b9e\u9645\u8ba1\u7b97\u9762\u79ef')),
                ('remark', models.TextField(default='', verbose_name='\u5907\u6ce8')),
                ('purpose', models.TextField(default='', verbose_name='\u623f\u95f4\u7528\u9014')),
                ('asset', models.TextField(default='', verbose_name='\u8d44\u4ea7')),
                ('boundary', models.CharField(default='', max_length=30, verbose_name='\u623f\u95f4\u8fb9\u754c')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpaceManage.RoomAssignment', verbose_name='\u7a7a\u95f4\u5206\u914d')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpaceManage.CategoryRoom', verbose_name='\u623f\u95f4\u7c7b\u578b')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nuser.department', verbose_name='\u4f7f\u7528\u90e8\u95e8ID')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpaceManage.SpaceFloor', verbose_name='\u697c\u5c42ID')),
            ],
            options={
                'verbose_name': '\u623f\u95f4',
                'verbose_name_plural': '\u623f\u95f4',
            },
        ),
        migrations.CreateModel(
            name='SpaceZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='\u5206\u533a\u540d\u79f0')),
                ('remark', models.TextField(default='', verbose_name='\u5907\u6ce8')),
                ('parentSpace', models.ForeignKey(blank=True, help_text='\u7236\u76ee\u5f55', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='SpaceManage.SpaceZone', verbose_name='\u7236\u5206\u533a\u7ea7\u522b')),
                ('rooms', models.ManyToManyField(blank=True, related_name='Zone', to='SpaceManage.SpaceRoom')),
            ],
            options={
                'verbose_name': '\u5206\u533a',
                'verbose_name_plural': '\u5206\u533a',
            },
        ),
        migrations.AddField(
            model_name='spaceibeacon',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpaceManage.SpaceRoom', verbose_name='\u5173\u8054\u623f\u95f4'),
        ),
    ]
