# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-07 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelManage', '0001_initial'),
        ('SpaceManage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spacefloor',
            old_name='model_Url',
            new_name='facility',
        ),
        migrations.AddField(
            model_name='spacefloor',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u9762\u79ef'),
        ),
        migrations.AddField(
            model_name='spacefloor',
            name='coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u7cfb\u6570'),
        ),
        migrations.AddField(
            model_name='spacefloor',
            name='description',
            field=models.TextField(default='', verbose_name='\u697c\u5c42\u63cf\u8ff0'),
        ),
        migrations.AddField(
            model_name='spacefloor',
            name='level',
            field=models.CharField(default='', max_length=64, verbose_name='\u6807\u9ad8'),
        ),
        migrations.AddField(
            model_name='spacefloor',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Floor', to='ModelManage.PrecastBeam'),
        ),
        migrations.AddField(
            model_name='spacefloor',
            name='sign',
            field=models.CharField(default='', max_length=64, verbose_name='\u6807\u8bb0'),
        ),
    ]
