# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-06 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SpaceManage', '0001_initial'),
        ('DeviceManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urltype1', models.CharField(choices=[(b'floor', b'floor'), (b'mepsystemtype', b'mepsystemtype'), (b'space', b'space'), (b'device', b'device'), (b'yuanqu', b'yuanqu'), (b'jifang', b'jifang'), (b'camera', b'camera')], max_length=256, null=True, verbose_name='\u6a21\u578b\u7c7b\u578b')),
                ('urlid', models.IntegerField()),
                ('url', models.CharField(max_length=256, null=True, verbose_name='\u6a21\u578b\u5730\u5740')),
                ('nexturl', models.CharField(max_length=256, null=True, verbose_name='\u53cc\u6a21\u578b\u7b2c\u4e8c\u4e2a\u6a21\u578b\u5730\u5740')),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SpaceManage.SpaceBuilding')),
            ],
            options={
                'verbose_name': '\u6a21\u578b\u8868',
                'verbose_name_plural': '\u6a21\u578b\u8868',
            },
        ),
        migrations.CreateModel(
            name='ModelUrl2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbid', models.IntegerField(blank=True, null=True, verbose_name='\u6784\u4ef6forgedbid')),
            ],
            options={
                'db_table': 'ModelManage_ModelUrl2Model',
            },
        ),
        migrations.CreateModel(
            name='PbGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=64, verbose_name=b'\xe7\xbb\x84\xe5\x90\x8d')),
            ],
            options={
                'db_table': 'ModelManage_pbgroup',
                'verbose_name': '\u6784\u4ef6\u5206\u7ec4\u8868',
                'verbose_name_plural': '\u6784\u4ef6\u5206\u7ec4\u8868',
            },
        ),
        migrations.CreateModel(
            name='PbGroupRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ModelManage_pbgrouprelation',
                'verbose_name': '\u6784\u4ef6\u4e0e\u5206\u7ec4\u5173\u7cfb',
                'verbose_name_plural': '\u6784\u4ef6\u4e0e\u5206\u7ec4\u5173\u7cfb',
            },
        ),
        migrations.CreateModel(
            name='PBMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('specification', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'\xe8\xa7\x84\xe6\xa0\xbc')),
                ('size', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'\xe6\x9d\x90\xe6\x96\x99\xe5\xb0\xba\xe5\xaf\xb8')),
            ],
            options={
                'db_table': 'ModelManage_pbmaterial',
                'verbose_name': '\u6784\u4ef6\u6750\u6599\u8868',
                'verbose_name_plural': '\u6784\u4ef6\u6750\u6599\u8868',
            },
        ),
        migrations.CreateModel(
            name='PBStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'db_table': 'ModelManage_pbstatus',
                'verbose_name': '\u6784\u4ef6\u72b6\u6001\u8868',
                'verbose_name_plural': '\u6784\u4ef6\u72b6\u6001\u8868',
            },
        ),
        migrations.CreateModel(
            name='PBType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
                ('classfication_code', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe7\xbc\x96\xe7\xa0\x81')),
                ('sign', models.CharField(blank=True, max_length=60, null=True, verbose_name=b'\xe6\xa0\x87\xe8\xae\xb0')),
                ('familyname', models.CharField(blank=True, max_length=60, null=True, verbose_name=b'\xe6\x97\x8f\xe5\x90\x8d\xe7\xa7\xb0')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('isprebuilt', models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe9\xa2\x84\xe5\x88\xb6')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModelManage.PBMaterial', verbose_name=b'\xe6\x9d\x90\xe6\x96\x99')),
            ],
            options={
                'db_table': 'ModelManage_pbtype',
                'verbose_name': '\u6784\u4ef6\u7c7b\u578b\u8868',
                'verbose_name_plural': '\u6784\u4ef6\u7c7b\u578b\u8868',
            },
        ),
        migrations.CreateModel(
            name='PrecastBeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=64, unique=True, verbose_name=b'GUID')),
                ('revitfilename', models.CharField(blank=True, max_length=60, null=True, verbose_name=b'Revit\xe6\x96\x87\xe4\xbb\xb6\xe5\x90\x8d')),
                ('elementid', models.CharField(blank=True, max_length=60, null=True, verbose_name=b'ElementID')),
                ('systemlmvdbid', models.IntegerField(blank=True, null=True, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9flmvdbid')),
                ('floorlmvdbid', models.IntegerField(blank=True, null=True, verbose_name=b'\xe5\x88\x86\xe5\xb1\x82lmvdbid')),
                ('systematic_diagram_lmvdbid', models.IntegerField(blank=True, null=True, verbose_name=b'\xe6\x9c\xba\xe7\x94\xb5\xe7\xb3\xbb\xe7\xbb\x9f\xe5\x9b\xbe')),
                ('parkdbid', models.IntegerField(blank=True, null=True, verbose_name=b'\xe5\x9b\xad\xe5\x8c\xba\xe6\xa8\xa1\xe5\x9e\x8bdbid')),
                ('detaildbid', models.IntegerField(blank=True, null=True, verbose_name=b'\xe7\xb2\xbe\xe7\xbb\x86\xe6\xa8\xa1\xe5\x9e\x8bdbid')),
                ('number', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('curstatustime', models.DateTimeField(verbose_name=b'\xe5\xbd\x93\xe5\x89\x8d\xe7\x8a\xb6\xe6\x80\x81\xe6\x97\xb6\xe9\x97\xb4')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name=b'\xe9\x87\x8d\xe9\x87\x8f')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name=b'\xe4\xbd\x93\xe7\xa7\xaf')),
                ('width', models.FloatField(blank=True, null=True, verbose_name=b'\xe5\xae\xbd\xe5\xba\xa6')),
                ('height', models.FloatField(blank=True, null=True, verbose_name=b'\xe9\xab\x98\xe5\xba\xa6')),
                ('length', models.FloatField(blank=True, null=True, verbose_name=b'\xe9\x95\xbf\xe5\xba\xa6')),
                ('sign', models.CharField(blank=True, max_length=60, null=True, verbose_name=b'\xe6\xa0\x87\xe8\xae\xb0')),
                ('pbposition_x', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name=b'\xe6\x9e\x84\xe4\xbb\xb6\xe4\xbd\x8d\xe7\xbd\xaex')),
                ('pbposition_y', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name=b'\xe6\x9e\x84\xe4\xbb\xb6\xe4\xbd\x8d\xe7\xbd\xaey')),
                ('pbposition_z', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name=b'\xe6\x9e\x84\xe4\xbb\xb6\xe4\xbd\x8d\xe7\xbd\xaez')),
                ('description', models.CharField(blank=True, max_length=4000, null=True, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('drawnumber', models.CharField(blank=True, max_length=60, null=True, verbose_name=b'\xe5\x9b\xbe\xe7\xba\xb8\xe7\xbc\x96\xe5\x8f\xb7')),
                ('pbpostion', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe4\xbd\x8d\xe7\xbd\xae\xe5\xad\x97\xe7\xac\xa6\xe4\xb8\xb2')),
                ('parentguid', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe7\x88\xb6\xe6\x9e\x84\xe4\xbb\xb6GUID')),
                ('curstatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModelManage.PBStatus', verbose_name=b'\xe5\xbd\x93\xe5\x89\x8d\xe7\x8a\xb6\xe6\x80\x81')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpaceManage.SpaceFloor', verbose_name=b'\xe6\xa5\xbc\xe5\xb1\x82')),
                ('mepsystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DeviceManage.MepSystem', verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f')),
                ('pbtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModelManage.PBType', verbose_name=b'\xe6\x9e\x84\xe4\xbb\xb6\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('proom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpaceManage.SpaceRoom', verbose_name=b'\xe6\x88\xbf\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u6784\u5efa\u8868',
                'verbose_name_plural': '\u6784\u5efa\u8868',
            },
        ),
        migrations.CreateModel(
            name='RoomclassFication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('aliasName', models.CharField(max_length=64, verbose_name='\u522b\u79f0')),
                ('code', models.CharField(max_length=64, verbose_name='\u5206\u7c7b\u7f16\u7801')),
                ('relCbimCode', models.CharField(max_length=64, verbose_name='\u5bf9\u5e94\u56fd\u5bb6\u5206\u7c7b\u4f53\u7cfb')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelManage.RoomclassFication', verbose_name=b'\xe7\x88\xb6\xe5\x88\x86\xe7\xb1\xbb')),
                ('pbtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ModelManage.PBType', verbose_name='\u6784\u4ef6\u7c7b\u578b')),
            ],
            options={
                'db_table': 'SpaceManage_Knowledge_RoomclassFication',
                'verbose_name': '\u7a7a\u95f4\u77e5\u8bc6\u5e93',
                'verbose_name_plural': '\u7a7a\u95f4\u77e5\u8bc6\u5e93',
            },
        ),
        migrations.AddField(
            model_name='pbgrouprelation',
            name='pb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModelManage.PrecastBeam'),
        ),
        migrations.AddField(
            model_name='pbgrouprelation',
            name='pbgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModelManage.PbGroup'),
        ),
        migrations.AddField(
            model_name='pbgroup',
            name='pbtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModelManage.PBType', verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AddField(
            model_name='pbgroup',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpaceManage.SpaceZone', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe5\x88\x86\xe5\x8c\xba'),
        ),
        migrations.AddField(
            model_name='modelurl2model',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ModelUrl2Model', to='ModelManage.PrecastBeam'),
        ),
        migrations.AddField(
            model_name='modelurl2model',
            name='modelurl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelManage.ModelUrl'),
        ),
        migrations.AddField(
            model_name='modelurl',
            name='models',
            field=models.ManyToManyField(related_name='ModelUrl', through='ModelManage.ModelUrl2Model', to='ModelManage.PrecastBeam'),
        ),
    ]
