# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-06 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u57ce\u5e02')),
                ('region', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u533a\u57df')),
                ('street', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8857\u9053')),
                ('code', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7f16\u53f7')),
            ],
            options={
                'db_table': 'usermanagement_address',
                'verbose_name': '\u5730\u5740',
                'verbose_name_plural': '\u5730\u5740',
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u90e8\u95e8\u540d\u79f0')),
                ('telephone', models.IntegerField(blank=True, null=True, verbose_name='\u65b9\u5f0f')),
                ('color_code', models.CharField(default=b'#ff0000', max_length=8, verbose_name='\u6a21\u578b\u90e8\u95e8\u6e32\u67d3')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nuser.Address', verbose_name='\u529e\u516c\u5730\u5740')),
            ],
            options={
                'db_table': 'usermanagement_department',
                'verbose_name': '\u90e8\u95e8',
                'verbose_name_plural': '\u90e8\u95e8',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truename', models.CharField(blank=True, default=b'', max_length=16, verbose_name='\u6635\u79f0')),
                ('contract', models.CharField(blank=True, default=b'', max_length=16, verbose_name='\u7535\u8bdd')),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nuser.department', verbose_name='\u90e8\u95e8ID')),
            ],
            options={
                'db_table': 'usermanagement_user_profile',
                'verbose_name': '\u7535\u8bdd\u4e0e\u6635\u79f0',
                'verbose_name_plural': '\u7535\u8bdd\u4e0e\u6635\u79f0',
            },
        ),
    ]
